TugasKelompokPPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TugasKelompokPPWApp.urls')),
]

TugasKelompokPPWApp/urls.py
from django.urls import path
from django.contrib import admin
from .views import feedback_index, feedback_create
from . import views

app_name = 'TugasKelompokPPWApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='home'),
    path('form/', views.form, name='form'),
    path('form/afterform1.html/', views.afterForm, name='thanks'),
    path('register/', views.register, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('feedback/', feedback_index, name='feedback'),
    path('feedback-create/', feedback_create, name="feedbackCreate"),
    path('berita/', views.beritas, name='beritas'),
    path('hasil/', views.hasil, name='hasil'),
    path('hasil/data/', views.data,  name='data'),

    #path('updateLike/<int:id>',views.update_like,name='update_like'),
    path('getTipsTrick/', views.getTipsTrick, name='getTipsTrick')
]

TugasKelompokPPWApp/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your models here.
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
class Feedback(models.Model) :
    nama = models.TextField(max_length=20)
    pesan = models.TextField(max_length=1200)

    def get_dict(self):
        return {
            'nama':self.nama,
            'pesan':self.pesan
        }
    
    def __str__(self):
        return self.nama



class Relawan(models.Model):
    nama = models.TextField(max_length = 100)
    email = models.TextField(max_length = 30)
    alasan = models.TextField(max_length = 300)

class news(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    link = models.CharField(max_length=500)
    content = models.TextField()

TugasKelompokPPWApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import news



class FeedbackForm(forms.Form):
    nama = forms.CharField(label="Nama", widget=forms.Textarea(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Masukkan Nama Anda',
        'required': True,
        'id' : 'nama_input'
    }))

    pesan = forms.CharField(label="Tips & Trick", widget=forms.Textarea(attrs={
        'rows': 6,
        'style': 'resize:none;',
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Tulis feedback versi kamu!',
        'required': True,
        'id':'message_input'
    }))


class RelawanForm(forms.Form) :
    nama = forms.CharField(label="Nama", max_length = 25)
    email = forms.CharField(label="Email", max_length = 30)
    alasan = forms.CharField(label="Alasan", max_length = 300)

class berita(ModelForm):
    class Meta:
        model = news
        fields = '__all__'

TugasKelompokPPWApp/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Feedback, Relawan
from .forms import FeedbackForm, RelawanForm
from .models import Feedback,  news
from .forms import FeedbackForm, berita
import datetime
from pip._vendor import requests
import json

from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import CreateUserForm
from django.core import serializers
@csrf_exempt

def index(request):
    return render(request, 'index.html')

@login_required(login_url='/login/')
def form(request):
    myForm = RelawanForm()

    if request.method == 'POST':
        myForm = RelawanForm(request.POST)
        if myForm.is_valid():
            Relawan.objects.create(**myForm.cleaned_data)
            return redirect("TugasKelompokPPWApp:thanks")

    context = {
        'form' : myForm,
    }
    return render(request, 'form.html', context)

def afterForm(request):
    return render(request, "afterform1.html")

def register(request):
    if request.user.is_authenticated:
        return redirect('TugasKelompokPPWApp:home')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('TugasKelompokPPWApp:login')

        context = {'form' :form}
        return render(request, 'register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('TugasKelompokPPWApp:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('TugasKelompokPPWApp:home')
            else:
                messages.info(request, 'username or password is incorrect')

        context = {}
        return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('TugasKelompokPPWApp:home')

@login_required(login_url='/login/')
def feedback_index(request, *args, **kwargs):
    my_form = FeedbackForm(Feedback)
    feedbacks =Feedback.objects.all()

    context = {
        'form' : my_form,
        'feedbacks' : feedbacks
    }
    return render(request, "feedback.html", context)  

@login_required(login_url='/login/')
# def feedback_create(request):
#     my_form = FeedbackForm()

#     if request.method == 'POST':
#         my_form = FeedbackForm(request.POST)
#         if my_form.is_valid():
#             Feedback.objects.create(**my_form.cleaned_data)
#             return redirect("TugasKelompokPPWApp:feedback")

#     context = {
#         'form' : my_form,
#     }
#     return render(request, "feedback_create.html", context)  


@login_required(login_url='/login/')
def beritas(request):
    form = berita()
    context = {'form':form}
    if request.method == "POST":
        form = berita(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/hasil')
    return render(request, 'berita.html', context)

@login_required(login_url='/login/')
def hasil(request):
    result = news.objects.all()
    context = {'result':result}
    return render(request, 'hasil.html', context)

@login_required(login_url='/login/')
def data(request):
    url = request.GET['q']
    ret = serializers.serialize('json', news.objects.filter(title__icontains=url))

    data = json.loads(ret)
    return JsonResponse(data,safe=False)

# #def detail_post(request, id):
#     thepost = Feedback.objects.get(id=id)
#     likes = len(Like.objects.filter(post = thepost))
#     context = {
#         "post" : thepost,
#         "like" : likes,
#     }
#     return render(request, "feedback.html", context)

# def update_like(request, id):
#     post_like = len(Like.objects.filter(post=Feedback.objects.get(id=id)))
#     return JsonResponse(post_like, safe=False)


def feedback_create(request):
    my_form = FeedbackForm()
    response = {}
    if request.method == 'POST':
        # print("APA AJA")
        if request.is_ajax():
            my_form = FeedbackForm(request.POST)
            print("aaaaaaaaaaaaaaaaaa")
            
            if my_form.is_valid():
                print("zzzzzzzzzzzzzzzzzzzzzzzz")
                Feedback.objects.create(**my_form.cleaned_data)
                return JsonResponse({'success':True})
        return JsonResponse({'success':True})

    context = {
        'form' : my_form,
    }
    print("bbbbbbbbb")
    return render(request, "feedback_create.html", context)  


def getTipsTrick(request):
    userReq = Feedback.objects.all().values()
    lst = list(userReq)
    print(lst)
    return JsonResponse(lst, safe=False)

TugasKelompokPPWApp/templates/afterform1.html
{% extends "navbar.html" %}
<!DOCTYPE html>
<html lang="en">

{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="static/form.css">
    <title>Document</title>
    <style>
        body{
            background-image: url("afterform_bg.png");
            background-size: cover;
        }
    </style>
</head>
<body>
</body>
{% endblock %}
</html>

TugasKelompokPPWApp/templates/berita.html
{% extends "navbar.html" %}

{% load static %}

{% block meta %}
<title>berita</title>
{% endblock meta %}

{% block content %}
<form method="POST">
<table>
    {% csrf_token %}
    {{form.as_table}}
</table>
    <input type="submit" value="tambah">
</form>
{% endblock content %}

TugasKelompokPPWApp/templates/feedback.html
{% extends "navbar.html" %}
{% load static %}
{% block content %}



    <div class="mainpage d-flex flex-column">

        <div class="d-flex flex-column">
            <div id="middleSection" style="margin-bottom: 30px;">
                <div class="ui search">
                    <div class="ui icon input">
                        <input id="input-name" class="prompt" type="text" placeholder="Search Name">
                        <i class="search icon"></i>
                    </div>
                    <div class="results"></div>
                </div>
            </div>

            <div id= "message">
                {% for feedback in feedbacks %}
                <div class="card1 mb-4 mx-5 entry">
                
                    <div class="card-header " style="background-color:  rgb(163, 202, 200); border-radius: 15px;">
                        {{feedback.nama}}
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ feedback.pesan }}</p>
                    </div>
               
                </div>
                {% endfor %}
            </div>
        <div class="mt-5 ml-5">
            <center><a class="button-class" role="button"  href="{% url 'TugasKelompokPPWApp:feedbackCreate' %}">add feedback</a></center>
        </div>
        

        </div>
    </div>

<script>
    $(function() {
        $('#input-name').keyup(function() {
            var keyword = $('#input-name').val();
            $.ajax({
                method: 'GET',
                url: '/getTipsTrick/',
                dataType: 'json',
                success: function(data) {
                    $('#message').empty();
                    var html = '';
                    console.log("haiiiiiii")
                    if (data.length === 0) {
                        html += '<h3 class="txt-setting">We are sorry, there aren\'t any tips & trick.</h3>';
                        $('#message').append(html);
                    } else {
                        for (var i = 0; i < data.length; i++) {
                            if ((data[i]['nama']).includes(keyword)) {
                                html += '<div class="card1 mb-4 mx-5 entry ">';
                                html = html + '<h2>' + data[i]['nama'] + '</h2>';
                                html = html + '<p>' + data[i]['pesan'] + '</p>' + '</div>';
                            }
                        }
                        $('#message').append(html);
                        // console.log(data);
                    }
                    // console.log(data);
                    // console.log(data.length);
                }
            })
        })
    })

    
</script>


{% endblock content %}

TugasKelompokPPWApp/templates/feedback_create.html
{% extends "navbar.html" %}
{% load static %}
{% block content %}

<div class="mainpage2"> 
        <div class="d-flex flex-column feedbackform">
            <h1 class="mt-3 add">Masukkan feedback anda untuk website kami</h1>
            <form action = '' method="POST" id= "feedbackform">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <!-- <input type="submit" id = "submitBtn" class="button-submit mx-auto" value="SUBMIT"> -->
                <button type="button" class="tombol" id="submitBtn">Submit</button>
            </form>
        </div>
        <div class="d-flex justify-content-center">
            <a role="button" class="button-create"  href="{% url 'TugasKelompokPPWApp:feedback' %}">VIEW FEEDBACK</a>
        </div>
</div>

<script>
$(document).ready(function() {
    $("#submitBtn").click(function() {
        $.ajax({
            type: "POST",
            url: "/feedback-create/",
            data: $("#feedbackform").serialize(),
            success: function(response) {
                $("#nama_input").val("")
                $("#message_input").val("")
                $("#input-name").trigger("keyup");
            }
        });
    });
})
</script>
{% endblock content %}

TugasKelompokPPWApp/templates/form.html
{% extends "navbar.html" %}
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
  {% block content %}
        <body class="body1">
                <div class="container1">
                  <form action="" method="POST">
                  <div class="row">
                    <div class="col-25">
                    <label for="name">Nama</label>
                    </div>
                    <div class="col-75">
                    <input type="text" id="fname" name="name" placeholder="Tulis nama..">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                    <label for="femail">Email</label>
                    </div>
                    <div class="col-75">
                    <input type="text" id="email" name="email" placeholder="Tulis email..">
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class="col-25">
                    <label for="freason">Alasan</label>
                    </div>
                    <div class="col-75">
                    <textarea id="reason" name="reason" placeholder="Tulis alasanmu.." style="height:200px"></textarea>
                    </div>
                  </div>
                  <div class="row">
                    <a href="afterform1.html">
                        <input type="button" value="Submit">
                    </a>
                  </form>
                  </div>
                </div>
                
                
                
                </body>
                {% endblock %}   
</body>

</html>

TugasKelompokPPWApp/templates/hasil.html
{% extends "navbar.html" %}

{% load static %}

{% block meta %}
<title>hasil</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock meta %}

{% block content %}

<input id="keyword" placeholder="judul berita">

<div id="daftar_berita">

{% for i in result %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{i.title}}</h5>
            <p class="card-text">{{i.content}}</p>
            <a href="{{i.link}}" class="btn btn-primary">{{i.link}}</a>
        </div>
    </div>
{% endfor %}

</div>

<a href="{% url 'TugasKelompokPPWApp:beritas' %}" class="btn btn-primary">Tambah Artikel</a>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    $("#keyword").keyup(function(){
        var inp = $("#keyword").val();
        $.ajax({
        
            url: '/hasil/data/?q='+inp,
            success:function(data) {
                console.log(data)
                var array_items = data;
                $("#daftar_berita").empty();
                for (i = 0; i<array_items.length; i++) {
                    var judul_berita = array_items[i].fields.title;
                    var author_berita = array_items[i].fields.author;
                    var konten_berita = array_items[i].fields.content;
                    var link_berita = array_items[i].fields.link;
                    $("#daftar_berita").append("<div class=\"card\"><div class=\"card-body\"><h5 class=\"card-title\">"+judul_berita+"</h5><p class=\"card-text\">"+konten_berita+"</p><a href=\""+link_berita+"\" class=\"btn btn-primary\">"+link_berita+"</a></div></div>");
                }
            }
        });
    });
</script>
{% endblock content %}

TugasKelompokPPWApp/templates/index.html
{% extends "navbar.html" %}
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
</head>

<body>
  {% block content %}
  <div class="homepage"></div>
  <div class="datacovid">
    <h1>Data-Data Panduan Covid-19</h1>
    <div class="row" style="margin-left: 600px;">
    <div class="col1">
      <h2>493.308</h2>
      <p style="font-size: 25px;">POSITIF</p>
    </div>
    <div class="col2">
      <h2>15.774</h2>
      <p style="font-size: 25px">MENINGGAL</p>
    </div>
    <div class="col3">
      <h2>413.955</h2>
      <p style="font-size: 25px">SEMBUH</p>
    </div>
    </div>
    <div class="jumbotron1 jumbotron-fluid">
        
            <div class="daftar">
                <p>YUK! Bersama kita cegah penularan Covid - 19 dengan bantu kami mendaftarkan diri kalian sebagai relawan untuk memberikan edukasi kepada masyarakat agar dapat mencegah virus ini terus menyebar</p>
                <a class="button" href="/form">Daftar Yuk!</a>
            </div>
         
    </div>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <p class="lead">Virus Corona atau severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) adalah virus yang menyerang sistem pernapasan. Penyakit karena infeksi virus ini disebut COVID-19. Virus Corona bisa menyebabkan gangguan ringan pada sistem pernapasan, infeksi paru-paru yang berat, hingga kematian.</p>
        </div>
    </div>

    <div class='slide'>
        <input type='radio' name='radio-set' checked='checked' />
        <img src="{% static 'masker.png' %}"  alt="Sheep 9">
      
        <input type='radio' name='radio-set' />
        <img src="{% static 'prosedur.png' %}"  alt="Sheep 9">
    </div>

    <div class="how">
        <p>
            Berdasarkan bukti ilmiah, COVID-19 dapat menular dari manusia ke manusia melalui droplet (percikan liur saat batuk atau bersin), tidak melalui udara atau airborne. WHO pernah menyebutkan tentang airborne precautions, yang ditujukan spesifik bagi tenaga medis, dikarenakan droplet dapat berubah menjadi partikel yang lebih kecil dengan beberapa prosedur tertentu, seperti nebulasi.</p>
    </div>

    <div class="tips">
      <h1>TIPS-TIPS MENCEGAH COVID-19</h1>
      <div class="row">
        <div class="column">
          
            <img id="gambartip" src="{% static 'ellips4.png' %}">
            <h2>MEMAKAI MASKER</h2>
          
        </div>
      
        <div class="column">
          
            <img id="gambartip" src="{% static 'ellips5.png' %}">
            <h2>MENCUCI TANGAN</h2>
          
        </div>
        
        <div class="column">
          
            <img id="gambartip" src="{% static 'ellips7.png' %}">
            <h2>JAGA JARAK</h2>
          
        </div>
      </div>

      <div class="row">
        <div class="column2">
          
            <img id="gambartip1" src="{% static 'ellips6.png' %}">
            <h2>MAKAN MAKANAN YANG SEHAT ATAU BERGIZI</h2>
          
        </div>
      
        <div class="column21">
          
            <img id="gambartip2" src="{% static 'ellips3.png' %}">
            <h2>BEROLAHRAGA</h2>
          
        </div>
      </div>
    </div>

    <div class="gejala">
      <h1>GEJALA COVID-19</h1>
      
      <div class="row2">
        <div class="column">
          
            <h2>BATUK</h2>
            <img id="gambargejala" src="{% static 'ellips8.png' %}">
          
        </div>
      
        <div class="column">
          
            <img id="gambargejala" src="{% static 'ellips9.png' %}">
            <h2>FLU</h2>
          
        </div>
      
        <div class="column">
          
            <h2>DEMAM</h2>
            <img id="gambargejala" src="{% static 'ellips10.png' %}">
          
        </div>
      </div>

      <br><br>

      <div class="row3">
        <div id="rev">
            <div class="column3">
                
                    <h2>LELAH</h2>
                    <h2>LESUH</h2>
                    <h2>LETIH</h2>
                
            </div>
            <div class="column3">
                
                    <img id="gambargejala1" src="{% static 'ellips11.png' %}">
                
            </div>
        </div>
        <div class="column3">
            
                <img id="gambargejala1" src="{% static 'ellips13.png' %}">
            
        </div>
        <div class="column31">
                <h2>SAKIT TENGGOROKAN</h2>
        </div>
      </div>

    </div>

{% endblock %}
</body>

</html>

TugasKelompokPPWApp/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;

		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				
				{% for message in messages %}
					<p>{{message}}</p>
				{% endfor %}
				
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'TugasKelompokPPWApp:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

TugasKelompokPPWApp/templates/navbar.html
<!doctype html>
<html lang="en">

{% load static %}

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'feedbackStyle.css' %}">
    <style>
      #tulisanCegahCovid {
        font-weight: bold;
        margin-left: 50px;
        font-size: 36px;
      }

      #Button {
        font-size: 20px;
        font-weight: bold;
        background-color: #D3D6F3;
        margin-right: 65px;
        outline: #D3D6F3;
        color: black;
        padding: 3px 35px;
        border-radius: 17px;
      }

      footer {
        background-color: black;
        text-align: center;
      }
      
      .maung{
        color:white;
        align-items: center;
        font-size: 20px;
      }

      .cegahcovid{
        color: white;
        align-items: center;
        font-size: 30px;
      }
      #hello-msg{
        font-size: 18px;
        color: white;
        margin-right: 20px;
      }
    </style>
    
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #565A85;">
        <a class="navbar-brand" id="tulisanCegahCovid" href="#">Cegah Covid-19</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
              <a class="btn btn-default" id="Button" href="/home">Home</a>
              <a class="btn btn-default" id="Button" href="/feedback-create">Feedback</a>
              <a class="btn btn-default" id="Button" href="{% url 'TugasKelompokPPWApp:beritas' %}">Berita</a>
          </form>
        </div>  
        {% if user and user.is_authenticated %}
        <span id="hello-msg">Hello, {{request.user}}</span>
        <span><a id="Button" href="{% url 'TugasKelompokPPWApp:logout' %}">logout</a></span>
        {% else %}
        <span><a id="Button" href="{% url 'TugasKelompokPPWApp:login' %}">login</a></span>
        {% endif%}
      </nav>

      {% block content %}
      {% endblock %}

      <footer>
        <p class="cegahcovid">Cegah Covid-19</p>
        <p class="maung">maung.id</p>
      </footer>


      
       
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script-->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>